apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        "scheduler.alpha.kubernetes.io/name": data-aware-scheduler
        "scheduler.alpha.quobyte.com.data-aware/files": /var/lib/mysql
      labels:
        app: db
      name: db
    spec:
      containers:
        - name: db
          image: "mysql:5.7"
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysqlVolume
      volumes:
      - name: mysqlVolume
        quobyte:
          registry: registry:7861
          volume: MySQLVolume
