apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        "scheduler.alpha.kubernetes.io/name": data-aware-scheduler
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          resources:
            requests:
              cpu: "500m"
              memory: "128M"
