apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: data-aware-scheduler
  name: data-aware-scheduler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-aware-scheduler
      name: data-aware-scheduler
    spec:
      containers:
        - name: data-aware-scheduler
          image: johscheuer/data-aware-scheduler:0.0.2
          args: ["--config=/etc/scheduler/scheduler_config.yaml"]
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /var/lib/kubelet/plugins/kubernetes.io~quobyte
            name: plugin-dir
          - name: scheduler-config
            mountPath: /etc/scheduler/
      volumes:
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io~quobyte
      - name: scheduler-config
        configMap:
          name: scheduler-config