apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
      name: scheduler
    spec:
      containers:
        - name: scheduler
          image: johscheuer/data-aware-scheduler:0.0.1
          args: ["--config=/etc/scheduler/scheduler_config.yaml"]
          volumeMounts:
          - mountPath: /var/lib/kubelet/plugins/kubernetes.io~quobyte
            name: plugin-dir
          - name: scheduler-config
            mountPath: /etc/scheduler/
      volumes:
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io~quobyte
      - name: scheduler-config
        configMap:
          name: scheduler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler_config.yaml: |-
    incluster: True
    #kubeconfig: ./config
    backend: quobyte
    opts:
      apiserver: http://api.quobyte.svc.cluster.local
      mountpoint: /var/lib/kubelet/plugins/kubernetes.io~quobyte
      password: quobyte
      user: admin
      kubernetes: "True"
      namespace: quobyte
