apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        "scheduler.alpha.kubernetes.io/name": data-aware-scheduler
        "scheduler.alpha.quobyte.com.data-aware/files": testFile.bin
      labels:
        app: v
      name: test
    spec:
      containers:
        - name: test
          image: "nginx:1.11.1-alpine"
          resources:
            requests:
              cpu: "500m"
              memory: "128M"