apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-init-dd
spec:
  template:
    metadata:
      name: benchmark-init-dd
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark-init-dd
        image: ubuntu:16.04
        resources:
          limits:
            cpu: 2000m
            memory: 5Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        command:
          - /bin/bash
          - -xec
          - |
            rm -f /test/benchmark.bin
            dd if=/dev/zero of=/test/benchmark.bin bs=1G count=40
        volumeMounts:
            - name: dd-test
              mountPath: /test
      volumes:
        - name: dd-test
          quobyte:
            registry: registry:7861
            volume: dd-test
