apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-init-mysql
spec:
  template:
    metadata:
      name: benchmark-init-mysql
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark-init-mysql
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: benchmark-config
                key: root_password
          - name: MYSQL_BENCH_USER
            valueFrom:
              configMapKeyRef:
                name: benchmark-config
                key: bench_user
          - name: TABLE_SIZE
            valueFrom:
              configMapKeyRef:
                name: benchmark-config
                key: table_size
        resources:
          limits:
            cpu: 10
            memory: 32Gi
          requests:
            cpu: 10
            memory: 32Gi
        command:
          - /bin/bash
          - -xec
          - |
            docker-entrypoint.sh mysqld &
            apt-get -qq update
            apt-get -qq -y install sysbench
            # Add check if access is possible
            until mysqladmin -u${MYSQL_BENCH_USER} -p${MYSQL_ROOT_PASSWORD} status 2> /dev/null;
            do
                sleep 10
            done
            # Prepare Database
            mysql -u${MYSQL_BENCH_USER} -p${MYSQL_ROOT_PASSWORD} -e "CREATE SCHEMA test;"
            # TODO move this in configmap
            mysql -u${MYSQL_BENCH_USER} -p${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL max_connections=2000;"
            mysql -u${MYSQL_BENCH_USER} -p${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL wait_timeout=60;"
            mysql -u${MYSQL_BENCH_USER} -p${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL interactive_timeout=60;"

            #mysql -uroot -pmysecret -e "CREATE SCHEMA sbtest;"
            # Add Benchmark table
            sysbench --db-driver=mysql --test=oltp --oltp-table-size=${TABLE_SIZE} --mysql-db=test --mysql-user=${MYSQL_BENCH_USER} --mysql-password=${MYSQL_ROOT_PASSWORD} prepare
            #sysbench --db-driver=mysql --test=oltp --mysql-table-engine=innodb --oltp-table-size=${TABLE_SIZE} --mysql-host=localhost --mysql-port=3306 --mysql-user=${MYSQL_BENCH_USER} --mysql-password=${MYSQL_ROOT_PASSWORD} prepare
        volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-store
          quobyte:
            registry: registry:7861
            volume: mysql-store
