apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-simple-non-local
spec:
  template:
    metadata:
      name: benchmark-simple-non-local
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark-simple-non-local
        image: ubuntu:16.04
        env:
          - name: RES_FILE
            value: "simple_non_local.log"
        command:
          - /bin/bash
          - -xec
          - |
            apt-get -qq update
            apt-get -qq install -y fio
            mkdir -p /results/fio/
            fio --rw=read --name=test --bs=1M --filename=/test/benchmark.bin --size=20G --numjobs=1 &> /results/fio/${RES_FILE}
        resources:
          limits:
            cpu: 10
            memory: 32Gi
          requests:
            cpu: 10
            memory: 32Gi
        volumeMounts:
            - name: result-store
              mountPath: /results
            - name: simple-test
              mountPath: /test
      nodeSelector:
        kubernetes.io/hostname: 10.241.0.4
      volumes:
        - name: simple-test
          quobyte:
            registry: registry:7861
            volume: simple-test
        - name: result-store
          quobyte:
            registry: registry:7861
            volume: result-store
