apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-simple-init
spec:
  template:
    metadata:
      name: benchmark-simple-init
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark-simple-init
        image: ubuntu:16.04
        resources:
          limits:
            cpu: 10
            memory: 32Gi
          requests:
            cpu: 10
            memory: 32Gi
        command:
          - /bin/bash
          - -xec
          - |
            apt-get -qq update
            apt-get -qq install -y fio
            rm -f /test/benchmark.bin

            fio --rw=write --name=test --bs=1M --filename=/test/benchmark.bin --size=20G --numjobs=1
        volumeMounts:
            - name: simple-test
              mountPath: /test
      volumes:
        - name: simple-test
          quobyte:
            registry: registry:7861
            volume: simple-test
